spring:
  application:
    name: cache-redis
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/cache_redis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: MyNewPass4!
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456
    database: 0
    timeout: 10000
#logback配置
logging:
  file: cache-redis.log
  level:
    org.zxl.shizhan.cacheredis: debug
server:
  port: 8761